services:
  - type: web
    name: mercarof-backend
    env: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: mercarof-backend
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mercarof-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mercarof-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mercarof-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mercarof-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mercarof-db
          property: password
      - key: FRONTEND_URL
        sync: false

databases:
  - name: mercarof-db
    databaseName: mercarof
    user: mercarof
